export const emotionEmojis = {
    anxious: {
      emoji: "🌪️",
      mood: "Confused",
      response: "It seems like you're feeling a bit overwhelmed. Want to talk about it?",
    },
    upset: {
      emoji: "💔",
      mood: "Hopelessness",
      response: "I'm sorry you're feeling let down. Do you want to share what's troubling you?",
    },
    sleepy: {
      emoji: "😴 ",
      mood: "Exhausted",
      response: "You sound really drained. Is there something I can do to help lighten the load?",
    },
    meh: {
      emoji: "😐",
      mood: "Disconnected",
      response: "Feeling disconnected or indifferent can be tough. What's been going on?",
    },
    anger: {
      emoji: "😡",
      mood: "Angry",
      response: "I understand you're feeling frustrated. What's on your mind?",
    }
  };

  export const commonEmojis = [
    "😊",
    "😃",
    "😄",
    "🙂",
    "😁",
    "😢",
    "😭",
    "😥",
    "☹️",
    "😔",
    "😰",
    "😨",
    "😱",
    "😟",
    "😦",
    "😠",
    "😡",
    "💢",
    "😤",
    "😣",
    "😫",
    "😪",
    "🥱",
    "😮‍💨",
    "🌟",
    "❤️",
    "💕",
    "✨",
    "👍",
    "🙏",
  ];  